export const Users = [
  {
    id: 1,
    profilePicture: "person/1.jpeg",
    username: "Safak Kocaolu",
  },
  {
    id: 2,
    profilePicture: "person/2.jpeg",
    username: "Alice",
  },
  {
    id: 3,
    profilePicture: "person/3.jpeg",
    username: "Anne",
  },
  {
    id: 4,
    profilePicture: "person/4.jpeg",
    username: "William",
  },
  {
    id: 5,
    profilePicture: "person/5.jpeg",
    username: "Robert",
  },
  {
    id: 6,
    profilePicture: "person/6.jpeg",
    username: "Lily",
  },
  {
    id: 7,
    profilePicture: "person/7.jpeg",
    username: "Mary",
  },
  {
    id: 8,
    profilePicture: "person/8.jpeg",
    username: "James",
  },
  {
    id: 9,
    profilePicture: "person/9.jpeg",
    username: "Helen",
  },
  {
    id: 10,
    profilePicture: "person/10.jpeg",
    username: "Frank",
  },
];

export const Posts = [
  {
    id: 1,
    desc: "Love for all, Hatred for none.",
    photo: "post/1.jpeg",
    date: "5 mins ago",
    userId: 1,
    like: 32,
    comment: 9,
  },
  {
    id: 2,
    desc: "Have nice breakfast.",
    photo: "post/2.jpeg",
    date: "15 mins ago",
    userId: 3,
    like: 17,
    comment: 16,
  },
  {
    id: 3,
    desc: "",
    photo: "post/3.jpeg",
    date: "45 mins ago",
    userId: 6,
    like: 19,
    comment: 4,
  },
  {
    id: 4,
    desc: "Happy day.",
    photo: "post/4.jpeg",
    date: "59 mins ago",
    userId: 4,
    like: 100,
    comment: 17,
  },
  {
    id: 5,
    desc: "They are beautiful.",
    photo: "post/5.jpeg",
    date: "27 mins ago",
    userId: 10,
    like: 31,
    comment: 17,
  },
  {
    id: 6,
    desc: "I love cat <3",
    photo: "post/6.jpeg",
    date: "15 mins ago",
    userId: 9,
    like: 11,
    comment: 2,
  },
  {
    id: 7,
    desc: "",
    photo: "post/7.jpeg",
    date: "35 mins ago",
    userId: 5,
    like: 10,
    comment: 91,
  },
  {
    id: 8,
    desc: "Beautiful sunset.",
    photo: "post/8.jpeg",
    date: "46 mins ago",
    userId: 1,
    like: 32,
    comment: 9,
  },
  {
    id: 9,
    desc: "I love u",
    photo: "post/9.jpeg",
    date: "35 mins ago",
    userId: 7,
    like: 100,
    comment: 38,
  },
  {
    id: 10,
    desc: "",
    photo: "post/10.jpeg",
    date: "25 mins ago",
    userId: 4,
    like: 18,
    comment: 19,
  },
];
